apiVersion: v1
kind: Pod
metadata:
  name: network-share-pod
spec:
  containers:
  - name: spring-boot
    image: gentledev10/spring-boot-docker
  - name: ubuntu-curl
    image: gentledev10/ubuntu-curl
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(curl -s localhost:8080); sleep 5; done"]