apiVersion: v1
kind: Pod
metadata:
  name: single-container-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 1; done"]