apiVersion: v1
kind: Pod
metadata:
  name: volume-share-pod
spec:
  containers:
  - name: ubuntu1
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello1 >> /ubuntu1/test.log; sleep 5; done"]
    volumeMounts:
    - mountPath: /ubuntu1
      name: test-volume
  - name: ubuntu2
    image: ubuntu
    command: ["/bin/sh"]
    args: ["-c", "tail -f /ubuntu2/test.log"]
    volumeMounts:
    - mountPath: /ubuntu2
      name: test-volume
  volumes:
  - name: test-volume
    emptyDir: {}